export enum ContentType {
    JSON = "application/json",
    HTML = "text/html",
    TEXT = "text/plain",
    CSS = "text/css",
    JAVASCRIPT = "text/javascript",
    PNG = "image/png",
    JPEG = "image/jpeg",
    SVG = "image/svg+xml",
    ICO = "image/x-icon",
    XML = "application/xml",
    PDF = "application/pdf",
    ZIP = "application/zip",
    GIF = "image/gif",
    MP3 = "audio/mpeg",
    MPEG = "video/mpeg",
    MP4 = "video/mp4",
    OGG = "audio/ogg",
    WEBM = "video/webm",
    WAV = "audio/wav",
    WEBP = "image/webp",
    FORM = "application/x-www-form-urlencoded",
    MULTIPART = "multipart/form-data",
    STREAM = "application/octet-stream",
    NONE = "none",
    }